apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicontagem
  labels:
    app: apicontagem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apicontagem
  template:
    metadata:
      labels:
        app: apicontagem
    spec:
      containers:
      - name: apicontagem
        image: fonsecadevops.azurecr.io/apicontagem
        env:
          - name: TesteAmbiente
            value: Teste utilizando o Azure Kubernetes Service (AKS) com variaves de ambiente no kubernetes
        ports:
        - containerPort: 80
